name: smart-dog-door

services:
  # https://github.com/mrlt8/docker-wyze-bridge
  wyze-bridge:
    image: mrlt8/wyze-bridge:latest
    container_name: wyze-bridge
    restart: unless-stopped
    ports:
      - "1935:1935"     # RTMP
      - "8554:8554"     # RTSP
      - "8888:8888"     # HLS
      - "5001:5000"     # Web UI
    environment:
      - WB_USERNAME=username        # WebUI username
      - WB_PASSWORD=password # WebUI password
      - WB_AUTH=true            # Enable WebUI authentication
      - WYZE_EMAIL=${WYZE_EMAIL}
      - WYZE_PASSWORD=${WYZE_PASSWORD}
      - API_ID=${WYZE_KEY_ID}
      - API_KEY=${WYZE_API_KEY}
    volumes:
      - wyze-config:/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  wyze-config: