
services:
  wyze-bridge:
    image: mrlt8/wyze-bridge:latest
    container_name: wyze-bridge
    restart: unless-stopped
    ports:
      - "1935:1935"     # RTMP
      - "8554:8554"     # RTSP
      - "8888:8888"     # HLS
    environment:
      - WYZE_EMAIL=${WYZE_EMAIL}
      - WYZE_PASSWORD=${WYZE_PASSWORD}
    devices:
      - /dev/video0:/dev/video0 # optional, only if needed
    volumes:
      - wyze-config:/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  wyze-config: